[package]
name = "parsemacro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
[dependencies]
anyhow = "1.0.79"
darling = "0.20.5"
nom = "7.1.3"
quote = "1.0.35"
syn = "2.0.48"
